export const REQUEST_CITIES = 'REQUEST_CITIES'
export const FETCH_CITIES = 'FETCH_CITIES'
export const FAIL_FETCH_CITIES = 'FAIL_FETCH_CITIES'

export const FETCH_CITY = 'FETCH_CITY'

export const REQUEST_ITINERARIES = 'REQUEST_ITINERARIES'
export const FETCH_ITINERARIES = 'FETCH_ITINERARIES'
export const FAIL_FETCH_ITINERARIES = 'FAIL_FETCH_ITINERARIES'
