export const REQUEST_CITIES = 'REQUEST_CITIES';
export const FETCH_CITIES = 'FETCH_CITIES';
export const FAIL_FETCH_CITIES = 'FAIL_FETCH_CITIES';

export const FETCH_CITY = 'FETCH_CITY';

export const REQUEST_ITINERARIES = 'REQUEST_ITINERARIES';
export const FETCH_ITINERARIES = 'FETCH_ITINERARIES';
export const FAIL_FETCH_ITINERARIES = 'FAIL_FETCH_ITINERARIES';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
